# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aadf5f439d1b811c934982e8a646e8a07ddb3951ef5ccd0538aa2408150001c23688ee0e8337547e707fd5dc5cc6242e835ce28a52eb9e416de85a34d416a07

test:
  secret_key_base: ccbbf19d14122df0af8919513d4a6e5204e497b3b2f40eb764559cb3eec6a77cfe47870502153d76259424b661e51093d07c889e8f2f2c4ac605ad3f616af8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
